export * from './ForgotPassword/ForgotPassword'
export * from './IngredientPage/IngredientPage'
export * from './Login/Login'
export * from './MainPage/MainPage'
export * from './Profile/Profile'
export * from './Register/Register'
export * from './ResetPassword/ResetPassword'
export * from './UserOrdersPage/UserOrdersPage'
